djangoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:project_id>/', views.project, name='project')
]

projects/models.py
from django.db import models


# 项目总表
class Project(models.Model):
    # 项目名称
    project_name = models.CharField(max_length=100)
    # 单位名称
    company_name = models.CharField(max_length=100)
    # 总额度
    total_budget = models.FloatField()

    def __str__(self):
        return str(self.project_name) + '，总额度：' + str(self.total_budget) + '，剩余额度：' + str(self.budget_left())

    # 剩余额度
    def budget_left(self):
        budget = 0.0
        # 查找出所有的不是FAILED状态的明细，累加起来，用总额度减去它
        for detail in self.detail_set.all():
            if detail.status != Detail.Status.FAILED.name:
                budget += detail.budget
        return self.total_budget - budget


# 明细表
class Detail(models.Model):
    # 所属的项目，如果项目有明细，则该项目不能被删除，需要删除所有该项目的明细才能删除项目。
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    # 申请金额
    budget = models.FloatField()

    class Status(models.TextChoices):
        NEW = 'NEW', '申请已提交，等待审核'
        INTERNAL_ACCEPT = 'INTERNAL_ACCEPT', '内部审核通过'
        THIRD_PARTY = 'THIRD_PARTY', '材料已发给第三方公司'
        SUCCESS = 'SUCCESS', '第三方公司金额已发放'
        FAILED = 'FAILED', '申请失败'
    # 申请的状态
    status = models.CharField(max_length=100, choices=Status.choices, default=Status.NEW)

    def __str__(self):
        return str(self.project) + '，' + self.status_name() + '，申请金额：' + str(self.budget)

    def status_name(self):
        return Detail.Status[self.status].label

projects/views.py
from .models import Project, Detail
from django.shortcuts import render


# 展示所有项目的后台逻辑
def index(request):
    # 从数据库中查找所有的项目
    project_list = Project.objects.all()
    # 渲染页面发送给前端
    context = {'project_list': project_list}
    return render(request, 'index.html', context)


# 展示项目详情的后台逻辑
def project(request, project_id):
    # 从数据库中查找指定项目
    the_project = Project.objects.get(id=project_id)
    # 查找出改项目的所有申请详情
    detail_list = the_project.detail_set.all()
    # 渲染页面发送给前端
    context = {'project': the_project, 'detail_list': detail_list}
    return render(request, 'project.html', context)

projects/templates/index.html
<html>
<head>
    <title>查看所有项目</title>
</head>
<body>
    <table style="border: 1px solid black;">
        <tr>
            <th>项目名称</th>
            <th>单位名称</th>
            <th>总额度</th>
            <th>剩余额度</th>
        </tr>
        {% for project in project_list %}
        <tr>
            <td><a href="{% url 'projects:project' project.id %}">{{ project.project_name }}</a></td>
            <td>{{ project.company_name }}</td>
            <td>{{ project.total_budget }}</td>
            <td>{{ project.budget_left }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

projects/templates/project.html
<html>
<head>
    <title>项目详情-{{ project.project_name }}</title>
</head>
<body>
<h2>项目详情</h2>
<ul>
    <li>项目名称：{{ project.project_name }}</li>
    <li>单位名称：{{ project.company_name }}</li>
    <li>总额度：{{ project.total_budget }}</li>
    <li>剩余额度：{{ project.budget_left }} </li>
</ul>
<table style="border: 1px solid black;">
    <tr>
        <th>申请金额</th>
        <th>申请状态</th>
    </tr>
    {% for detail in detail_list %}
    <tr>
        <td>{{ detail.budget }}</td>
        <td>{{ detail.status_name }}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>